#this plugin made by me
# _____                               _
#|  ___|_ _ _ __         ___ ___   __| | ___
#| |_ / _` | '_ \ _____ / __/ _ \ / _` |/ _ \
#|  _| (_| | | | |_____| (_| (_) | (_| |  __/
#|_|  \__,_|_| |_|      \___\___/ \__,_|\___|
#Need help? Contact me
#discord: "Fαɳ. # 0066
#mail: shadowaxe94@gmail.com

#id de votr graiee! attention veillez obligatoirement mettre l'id d'une graine!!
id: 59

#Le nombre d'xp donné doit elle etre aleatoir? si OUI mettez true! si NON mettez le nombre a donné que vous désirez!!
aleatoire: "true"
